### PR TITLE
Fix Account Switcher on Mobile

### PR DESCRIPTION
**Pull request by harpreet9629**
Fixed Account Switcher on Mobile

### CODE REVIEW

**Comment by AdityaChaudhary0005** [comment]
loved your speed of working @harpreet9629 !

**Comment by redpartyhat** [comment]
Hi Harpreet, thanks for all your hard work on this! Unfortunately, I am still able to reproduce the issue in chrome with this fix.

**Comment by harpreet9629** [comment]
> 
> 
> Hi Harpreet, thanks for all your hard work on this! Unfortunately, I am still able to reproduce the issue in chrome with this fix.

Let me check, it works fine for me on mobile and pc

**Comment by lazynina** [comment]
Hi @harpreet9629 - thanks for the contributions.  PR #283 resolves the issue so I'm going to close this one out.

**Comment by harpreet9629** [comment]
> 
> 
> Hi @harpreet9629 - thanks for the contributions. PR #283 resolves the issue so I'm going to close this one out. The absolute positioning of the change account selector list was the culprit in this case.

Okay Thanks For Support Me :)

**Pull request closed without merging**
