### PR TITLE
Mars theme.ts

### PR DESCRIPTION
**Pull request by teambrixmusic**
🔴 Mars Theme was inspired by a recent quote by Grimes on Instagram saying, she was "Ready to die with the red dirt of mars beneath my feet." I thought also of the movies Dune and Total Recall. I felt it might make our favorite Teslans feel more at home on Bitclout with a native theme inspired by their aspiring future home planet. I went with a high tech led type of red link and button to employ the new button class and give that studio-esq Red-Light-Special look.

[It might also be a nice Valentines Day type of theme for Valentines screenshots. 💖]

I can't do a screenshot with the new merge of the button class, but it's red to match the links and I would love if anyone could make a screenshot for me if it's rejected or merged.

Welcoming any core team adjustments to logo or whatever else.

mars

### CODE REVIEW

**Comment by AdityaChaudhary0005** [comment]
@teambrixmusic i think there are some visibility issue with this theme ?
maybe a better color scheme ?

**Comment by tijno** [comment]
This one is a bit much for me too @teambrixmusic.

Maybe consider looking at some of the colour schemes for something like https://styles.ulysses.app/themes?order=likes could give inspiration of a good combination of colours.

**Comment by harpreet9629** [comment]
Here's suggestions

1. Use background color more dark
2. Text and links color to be lighter
3. Don't use too bright colors.

**Comment by teambrixmusic** [comment]
Thanks for the feedback @harpreet9629 @tijno @AdityaChaudhary0005 😊
Since this one was too bold for main, I can move it to my stylus repo. 
Is it rude to close a pull here on my end once submitted? 
I have 2 others I can commit.
Do you think I should bring these up in a CIP in the future?

**Pull request closed without merging**
