### PR TITLE
Fixes for Dark Mode

### PR DESCRIPTION
**Pull request by carsenk**
Just a few fixes for Dark Mode (Reclout hover and replying theme)

You can cherry pick my changes out of this if needed and I will fix up my repo

### CODE REVIEW

**Comment by tijno** [comment]
Im no readability expert but thoughts on [this post](https://bitclout.com/posts/691596f0c8b62c901f71b85efd64299fe9423b2acb73b9e92be8f36673b03bf1?feedTab=Global) ?

**Comment by carsenk** [comment]
I added several other fixes for Dark Mode in this PR....I also added a small animation for liking posts 💯

**Comment by carsenk** [comment]
> In think it makes sense to do animations as a separate pr and include some others eg the whole bottom bar?
> 
> Im no accessibility expert either so dont know effect of animation on that.
> 
> Would be worth putting some thought into that aspect.

I will do the rest in a separate repo, still working on this one to get modals corrected for Dark Mode, bunch of other little fixes people have been finding are in this as well

**Comment by maebeam** [comment]
Thanks for submitting these fixes! Would you be willing to remove the animations from this PR so I can merge this?

**Comment by carsenk** [comment]
> Thanks for submitting these fixes! Would you be willing to remove the animations from this PR so I can merge this?

Sure I can if you want, it just one animaton on liking, pure CSS. Do you want a separate PR for animations? I just pushed up the final fixes for comment modal styling for themes.

**Comment by maebeam** [comment]
The problem is the animation will render anytime the page loads not just when the user clicks the like button. Separating PRs into reasonably isolated / small chunks is appreciated.

**Comment by carsenk** [comment]
> The problem is the animation will render anytime the page loads not just when the user clicks the like button. Separating PRs into reasonably isolated / small chunks is appreciated.

Fair enough, good point, I did just realize that, yes, I will make a separate PR, I removed the code for it to initialize, hopefully that is sufficient until it is finished? I will open a new PR after this gets merged and rebase my repo

**Comment by carsenk** [comment]
This is good to go, will open different PRs in future @maebeam

**Comment by carsenk** [comment]
New cleaned PR https://github.com/bitclout/frontend/pull/109

**Pull request closed without merging**
