### PR TITLE
Adds Image/Video Replying to Comments and Reclout Quotes

### PR DESCRIPTION
**Pull request by carsenk**
This adds in video/image replying to comments and reclout quotes! This will be extremely useful for all of us wanting to be able to reply with an image or gif!

Previews:
image

f3a7315c86

Example link of posted content using this feature: https://bitclout.com/posts/51ee8e495286f15cefee288e4cca85dc76e55afdf2e64f694546ed83d4fa313b

### CODE REVIEW

**Comment by tijno** [comment]
You saw #38 ?

**Comment by carsenk** [comment]
> You saw #38 ?

Yes fixed it up to also include comment posting, it is a must have for sure

**Comment by tijno** [comment]
Yeah but that originally included embeds in comments but was then specifically excluded

https://github.com/bitclout/frontend/pull/38/commits/89ec867a872040914789a78aecdf767160e303c3

So probably worth @lazynina confirming why it was excluded.

**Comment by carsenk** [comment]
So shoutout @lazynina on this one for sure!

> Yeah but that originally included embeds in comments but was then specifically excluded
> 
> [89ec867](https://github.com/bitclout/frontend/commit/89ec867a872040914789a78aecdf767160e303c3)
> 
> So probably worth @lazynina confirming why it was excluded.

I see no issue with having embeds in comments? Seems to work fine as shown in screenshot above, you can view the reclout quotes embeds on main production node, just not comment images, but it is confirmed working in this, you can feel free to test it out @tijno and let us know!

**Comment by tijno** [comment]
Just flagging my view - ive seen it work, and some of the other bitclout apps like cloutfeed support it. 

My point is - just because its possible, doesnt mean its the right thing to do.

**Comment by carsenk** [comment]
> Just flagging my view - ive seen it work, and some of the other bitclout apps like cloutfeed support it.
> 
> My point is - just because its possible, doesnt mean its the right thing to do.

Lol.....Well fair point, I would say I am on the other side of the spectrum here.

This NEEDS to be added, no question about it really....it is a pretty major feature to not have in an app trying to compete with these billion dollar empires...

No offense to all those apps, but they are going to want to figure out new business strategies now. lol

**Comment by enkayz** [comment]
> 
> 
> Just flagging my view - ive seen it work, and some of the other bitclout apps like cloutfeed support it.
> 
> My point is - just because its possible, doesnt mean its the right thing to do.

In some aspects, image replies can discourage actual discussion in a thread. Images also can be quite large and take up significant screen real estate, especially in a 'feed' style without a lot of screen width. I think being able to embed content in a comment is a good idea in certain situations but comments that are only images might work well on a PC screen with good real estate but are hard to syndicate across all other platforms.

We must also consider text-only platforms such as console, various readers and the like. What would be shown in place of an only-image comment? HTML alt-text for an image would be a required input to maintain the standard and that seems to go against the spirit of the 'image-comment'.

I would suggest that embed content in comments be a setting controlled by the user whom owns the original clout post, the setting would be per-clout with 'on/off/default' and a default setting available in the user profile. This way, users who want to run clout feeds full of meme images can do so, but it won't affect any existing clout feeds which rely on text UIs.

**Comment by carsenk** [comment]
@lazynina thoughts on this being added still? I think we should have the option to reply to posts with gifs and images, just like Twitter and other social media platforms?

I can clean up the conflicts

**Comment by carsenk** [comment]
This repo is all out of line at this point, will wait to see what @lazynina says, would really like to get this in for next update!

**Comment by carsenk** [comment]
Closing this PR for now as @lazynina and team are reviewing this still I believe and needs rebase/reopen

**Pull request closed without merging**
