### PR TITLE
Fixed Dark Theme Feed Post Dropdown Hover colors

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
Fixed Dark Theme Feed Post Dropdown Hover colors.

### CODE REVIEW

**Comment by barrymichaeldoyle** [comment]
Originally Looked Like this:

Screenshot 2021-06-08 at 08 47 03


After the style fix:

Screenshot 2021-06-08 at 08 46 32

**Comment by barrymichaeldoyle** [comment]
Screenshot 2021-06-08 at 09 14 34

Also proof that it doesn't break light theme styling :)

**Comment by carsenk** [comment]
Thank you for contributing! It needs to follow more of the current modular theming, already fixed in PR: https://github.com/bitclout/frontend/pull/100/files

**Comment by barrymichaeldoyle** [comment]
Been resolved in other PRs, closing...

**Pull request closed without merging**
