### PR TITLE
Add Recent Feed Tab

### PR DESCRIPTION
**Pull request by harpreet9629**
Here i tried my first PR :p 

Adding Recent Feed Tab :)

### CODE REVIEW

**Comment by tijno** [comment]
@harpreet9629 

1 - yea! nice one on your first PR.

2 - not sure why but the screenshot is not loading.

could you edit the reply and add it?

**Comment by harpreet9629** [comment]
Done

**Comment by derishaviar** [comment]
This is a great idea mrpeet!

**Comment by harpreet9629** [comment]
@lazynina what's the status of this please

**Comment by harpreet9629** [comment]
Please look at this also

**Comment by lazynina** [comment]
I don't know if we'd like to include this on bitclout.com.  There are a ton of posts and no moderation of that content.  Additionally, we'll be adding a third tab for NFTs when that functionality is released, so I think 4 tabs may be too much clutter for this page. 

@maebeam thoughts on this? I can be swayed, but I don't know that we want to add this recent tab at this time.

**Comment by maebeam** [comment]
For the time being I agree with @lazynina that we don't want to add a third tab to the browse page.

Thank you for all the PRs you've been submitting @harpreet9629. Keep you the great work :)

**Comment by harpreet9629** [comment]
But it's a most use able tab for all, with the help of this users can get latest posts, similar added on Facebook too,

We can add in left sidebar with the name Most Recent?

**Comment by AdityaChaudhary0005** [comment]
I think moderation is an issue @harpreet9629 in recent tab.

Let's not have NSWF content easily accessible on the site. That's why we have global tab moderated by admins.

**Pull request closed without merging**
