### PR TITLE
AutoComplete Mentions in Clouts & Comments

### PR DESCRIPTION
**Pull request by harpreet9629**
AutoComplete Mentions in Clouts & Comments Using angular-mentions package.
 I tried with a manual process but it has still 1 issue, So I used the package for this.

`npm install angular-mentions`

Screenshot_3

I hope Dev and everyone like this Feature :)

### CODE REVIEW

**Comment by tijno** [comment]
I Love this!!

but ... should this not follow CIP process as this ads a package and therefore is not a small change.

**Comment by harpreet9629** [comment]
Oh Okay, So Now first I have to post on CIP?

**Comment by AdityaChaudhary0005** [comment]
the feature we all wanted! Great work!
I agree with @Tijn though

**Comment by brootle** [comment]
very nice!

**Comment by tijno** [comment]
> Oh Okay, So Now first I have to post on CIP?

yes - mention this issue in in discussion topic and close this issue.

**Pull request closed without merging**
