### PR TITLE
When switching user stay on same page and reload

### PR DESCRIPTION
**Pull request by cat-ico**
When an account is switched the app always navigates to the browse page. This a bit user-unfriendly.
Also, the data is not reloaded, so when user A likes a post on a feed and switches to user B the like button stays toggled on in the UI.

This PR changes the behavior so that:
* The user stays on the same page when the account is switched
* The route is reloaded so that the data is updated for the current user

This also fixes issue #221

### CODE REVIEW

**Review by lazynina — CHANGES_REQUESTED** [review]
These lines alone don't refresh all the data based on the newly selected user.  For example, if I'm on the notifications page and I switch users, the notifications don't reload. 

The below line, if added to the constructor in this component, will reload the page and all data based on the new user.
```
this.router.routeReuseStrategy.shouldReuseRoute = () => false;
```

**Comment by maebeam** [comment]
Do we want to set `shouldReuseRoute` to `false` for all routes? If yes, let's see if we can do that once globally. If not, perhaps the right solution might be something like

```
this.router.navigate(['/']).then(() => { this.router.navigate([newRouterLink ]); })
```

**Comment by cat-ico** [comment]
@lazynina Strange, when I go to post detail and then to notifications, the reloading works as expected. But when I start at the notifications page it doesn't work.

I updated the fix as per @maebeam's suggestion.

Thank you both!

**Review by maebeam — APPROVED** [review]
Motto of the year is angular sucks. Looks good to me!

**Review by lazynina — APPROVED** [review]

**Comment by brootle** [comment]
> Motto of the year is angular sucks. Looks good to me!
you want to deploy ReactJS version of Bitclout client web app? the number of PRs would explode, seriously.

**Comment by maebeam** [comment]
@brootle I don't want to port the app to React but someone should!

**Pull request merged**
