### PR TITLE
cdd/ Cleanup of Theme Settings

### PR DESCRIPTION
**Pull request by connerdouglass**
This PR updates the Theme dropdown in Settings to dynamically list all available themes, instead of hard-coding them into the page HTML.

The benefit of this change is that future themes will have a smaller Git footprint. The `settings.component.html` file won't need to be edited for each new theme.

If this PR is merged, going forward themes just need to be created and added to the usual list in `app.module.ts`

### CODE REVIEW

**Comment by connerdouglass** [comment]
@carsenk I'd appreciate your input as well!

**Comment by carsenk** [comment]
@connerdouglass Looks great to me! +1 to this idea, simplifies adding additional themes, I will test it out here soon, but looks good to go from just a quick look through! THANK YOU! 🚀

**Comment by carsenk** [comment]
@lazynina @maebeam @diamondhands0 need review/merge 👍

**Review by lazynina — APPROVED** [review]
looks great and works like a charm. thanks @connerdouglass

**Comment by connerdouglass** [comment]
Thanks @lazynina and @carsenk!

**Pull request merged**
