### PR TITLE
De-duplicate infinite scrolling logic [part 2]

### PR DESCRIPTION
**Pull request by akutch**
## Description
Closes https://github.com/bitclout/frontend/issues/246

Updates the following components to use the `InfiniteScroller` class, as opposed to implementing their own `getDatasource()` methods:
- `CreatorProfileHodlersComponent`
- `CreatorsLeaderboardComponent`
- `ManageFollowsComponent`
- `DiamondPostsComponent`
- `TrendsComponent`

## Open questions
❓ ~How can I populate my local test node with more data (namely with additional creators)? Or is there another best practice for testing with realistic data?~

~^ If that's still a manual process and one of you have more in your test node, do you mind making sure the pages listed in the **Acceptance Criteria** section below are scrolling as expected with these changes?~ 

✅ I can use @tijno 's test node as he recommended [here](https://github.com/bitclout/frontend/pull/250#issuecomment-876152320)

## Acceptance Criteria
- [x] Creator profile holders are paginating as expected
- [x] Creators leaderboard is paginating as expected
- [x] Manage follows is paginating as expected
- [x] Diamond posts are paginating as expected
- [x] Trends are paginating as expected

## Screenshots
~❗These do not verify pagination works. The images are for reference for the **Acceptance Criteria** above~

Page | Before | After | Route
-|-|-|-
Creator profile holders | creator-coin-before | creator-coin-after | `http://localhost:4200/u/<username>?tab=creator-coin`
Creators leaderboard | leaderboard-before | leaderboard-after | `http://localhost:4200/creators`
Manage follows | followers-before | followers-after | `http://localhost:4200/u/<username>/following`
Diamond posts | diamond-before | diamond-after-actual | `http://localhost:4200/u/<username_a>/diamonds/<username_b>`
Trends | trend-before | trend-after |`http://localhost:4200/trends`

### CODE REVIEW

**Comment by teambrixmusic** [comment]
Nice work Anna

**Comment by tijno** [comment]
@akutch 

re:

> How can I populate my local test node with more data (namely with additional creators)? Or is there another best practice for testing with realistic data?

I guess you are using test net ? 

You dont need to run a full node for frontend dev.

You can just use your dev frontend with another full node.

So you see live data.

See this guide by @AdityaChaudhary0005 

https://devsclout.hashnode.dev/running-bitclouts-frontend-for-local-development-without-running-node

**Comment by harpreet9629** [comment]
Nice work appreciate it 👍

**Comment by akutch** [comment]
Running against @tijno's node worked perfectly. I did more manual testing and updated the gifs/description.

**Review by maebeam — APPROVED** [review]
Incredible work! Will wait for second review from @lazynina before merging

**Review by lazynina — APPROVED** [review]
:rocket: 

Thank you! this is awesome.

**Pull request merged**
