### PR TITLE
Fixes #302

### LINKED ISSUE #302: All white  ! Can’t see the quoted posts and many things !
81DEAB0E-0A84-4C60-940F-26DA11940557

### PR DESCRIPTION
**Pull request by JustifydWarrior**

### CODE REVIEW

**Comment by JustifydWarrior** [comment]
This isn't an actual conflict, just a change. not sure why it conflicts.

**Comment by maebeam** [comment]
Thanks for fixing this

**Comment by maebeam** [comment]
@JustifydWarrior I just merged this and it appears to not build correctly

https://buildkite.com/bitclout/frontend/builds/152#32dc3faf-779f-4569-ba4a-67a7b83b7202

**Comment by JustifydWarrior** [comment]
shit, it built once, then yeah it broke big time. 

there is a better fix... i just don't know how to make it work.

we really only need the class and attribute on the body tag as i mentioned in #302. 

we don't need it in any of the other places.

**Pull request merged**
