### PR TITLE
Share Post 

### PR DESCRIPTION
**Pull request by mvanhalen**
Adds a share post option in the post drop down menu using the built in [web share api](https://www.w3.org/TR/web-share/) .  Supported by Egde, Chrome and Safari

See screenshots:

in list:

single post thread:

detail after click/touch a native prompt will be opened by the browser:

mobile:
localhost_4200_posts_e17f98384111c7aec62640e80e6918893269e91264e35c7a2db2d2afd351d64f_feedTab=Global(iPhone 6_7_8 Plus) (1)

### CODE REVIEW

**Comment by tijno** [comment]
like it !!

**Comment by AdityaChaudhary0005** [comment]
great work @mvanhalen !

**Comment by iPaulPro** [comment]
Awesome! I'd even argue that a share button could replace the permalink button on desktop.

**Comment by mvanhalen** [comment]
Thanks all! @iPaulPro you mean the one next to the diamond? The native share prompt normally also shows a copy link option as one of the options. Favorite apps and contacts to share as well. Let´s first get this accepted and then add some more. I think a share option for profile page can be handy too. What would be a normally timeframe if core devs accept?

**Comment by iPaulPro** [comment]
> Thanks all! @iPaulPro you mean the one next to the diamond?

Yes exactly. Especially since the "Link to Post"  menu option is already there and,  as you said, there's an option in the share window to copy the link as well.

**Comment by AdityaChaudhary0005** [comment]
i have a question which i think is fine to ask here. Having heard rumours that new frontend is coming, i think these PRs by community devs is just waste, isn't it ? or am I wrong here ?

**Comment by tijno** [comment]
its not a rumour - its coming for sure.

ive read some posts suggesting sept for coinbase, with redesign before that. 

as we dont know scope of redesign i think its useful to continue iterating on small improvements here for now.

**Comment by mvanhalen** [comment]
> its not a rumour - its coming for sure.
> 
> ive read some posts suggesting sept for coinbase, with redesign before that.
> 
> as we dont know scope of redesign i think its useful to continue iterating on small improvements here for now.

@AdityaChaudhary0005 might have a point. But we don´t know the scope exactly. That is the real issue I think. Knowing what is coming can help us prepare better. In the meanwhile I agree with @tijno small changes like this can keep going on. But I would not start a big or medium change now without knowing the scope of the redesign. I do think a redesign is needed. Site has many usability issues, speed and others.

**Review by maebeam — APPROVED** [review]

**Review by lazynina — APPROVED** [review]

**Pull request merged**
