### PR TITLE
Update styles.scss

### PR DESCRIPTION
**Pull request by Jeanclaudeaoun**
Small color fix for reclout dropdown on dark-mode (hover)

### CODE REVIEW

**Comment by Jeanclaudeaoun** [comment]
> Small color fix for reclout dropdown on dark-mode (hover)

"Small fix" but important for dark-mode power users😂

**Comment by tijno** [comment]
Have you checked the other PRs waiting to be merged or go live? I think this ones already been sorted.

**Comment by Jeanclaudeaoun** [comment]
Yeah just checked! Already in another PR. my bitclout is @jeanclout

**Comment by tijno** [comment]
awesome gave you a follow

**Pull request closed without merging**
