### PR TITLE
Frontend New Design of Buttons, Sidebar's, Create Post, Feed Css

### PR DESCRIPTION
**Pull request by harpreet9629**
Here's 2nd PR 

In this PR, I changed Font, CSS on few things and tried to make it better and look nice.
Screenshot_2

Also, I changed CSS for Buttons, and changed buttons on the profile page.
Screenshot_3

### CODE REVIEW

**Comment by ShhubhamA** [comment]
The profile photo in the side switch account looks 👀

**Comment by lazynina** [comment]
@harpreet9629 There are a lot of changes in this PR - would you mind breaking up each change into its own PR? That way we can evaluate each change individually and determine whether or not we'd like to accept certain style changes.

Thanks for your efforts here!

**Comment by harpreet9629** [comment]
Ok i m adding new PR's for each section

**Comment by tijno** [comment]
@harpreet9629 thx for making these suggestions. 

Can you close this PR so it doesnt get mixed up with individual PRs.

**Pull request closed without merging**
