### PR TITLE
Actually fix #302

### LINKED ISSUE #302: All white  ! Can’t see the quoted posts and many things !
81DEAB0E-0A84-4C60-940F-26DA11940557

### PR DESCRIPTION
**Pull request by JustifydWarrior**
this moves the theme variables to the body tag so they work everywhere, including modals.

### CODE REVIEW

**Comment by JustifydWarrior** [comment]
this also reverts the #307 merge

**Comment by teambrixmusic** [comment]
It's all moving so fast. Once I have a chance to thoroughly familiarize myself with the new theming system I will be glad to help more. (I promised my kids a pool day today so my bad for tagging you all suddenly.) You're awesome for swooping in this way @JustifydWarrior

**Comment by teambrixmusic** [comment]
12f3

@JustifydWarrior Currently what it looks like when I hit reply to a Tiktok embed post on desktop windows 10 edge/chromium

**Comment by JustifydWarrior** [comment]
yeah the variables are "undefined" because they are declared in a container that the modal sits outside of.

this moves all the theme variables to the body tag so all the css can access them.

**Comment by JustifydWarrior** [comment]
You can see this change works on the live site by using the console:

```
let body = document.querySelector("body");
body.classList.add("light"); // or "dark" or whatever theme you're using
body.setAttribute("app-theme", "");
```

but you can only test the setting page works if you build it.

**Pull request merged**
