### PR TITLE
New Style of Icons in Notifications

### PR DESCRIPTION
**Pull request by harpreet9629**
Here's New Style for Icons in Notifications. I hope everyone likes this. :)

Screenshot_2

### CODE REVIEW

**Comment by AdityaChaudhary0005** [comment]
I like it but i think previous icons were better since they emphasised more on type of notifications (i.e, likes/diamonds)
I am interested in knowing what others think about it.

**Comment by teambrixmusic** [comment]
Tough call. I wonder how visible the icons would be on mobile at 100%
Esthetically, I think **this is far more attractive and modern**.
Functionally, I think it may render the icons too small on a phone.  :(

**Comment by harpreet9629** [comment]
> Tough call. I wonder how visible the icons would be on mobile at 100%
> Esthetically, I think **this is far more attractive and modern**.
> Functionally, I think it may render the icons too small on a phone.  :( 
> 

I agree, with you but i have 1 more option to make it better,

And in this on mobile i can make bigger size, so it won't too small or hidden

**Comment by AdityaChaudhary0005** [comment]
But what's wrong with the already existing notification icon?

I think it's unique and better in its own way :)

**Comment by harpreet9629** [comment]
> But what's wrong with the already existing notification icon?
> 
> I think it's unique and better in its own way :) 

There's nothing wrong with existing ui, but its suggestion, if like it will will be approve otherwise it will close.

**Pull request closed without merging**
