### PR TITLE
Change frontend to use a fallback route for default profile pics.

### PR DESCRIPTION
**Pull request by redpartyhat**
This fixes the bug noted by mp3 here: https://bitclout.com/posts/4488d9624f26409c802bce8e8355f989ebb11efe6a53ee5f4882a4c9cf74806c

### CODE REVIEW

**Comment by redpartyhat** [comment]
See PR for backend support here: https://github.com/bitclout/backend/pull/45

**Comment by slydisciplecom** [comment]
you're crushing it! :)

**Comment by slydisciplecom** [comment]
still seeing it btw

**Comment by carsenk** [comment]
> still seeing it btw

Not deployed to production server bitclout.com yet ;)

**Comment by slydisciplecom** [comment]
Sounds good. Hey while I have you here what do you think of
https://Name-Trade.com? It’s the first ever bitclout username trading
service being built on bitclout. I saw a current and speculative uptick in
the need for a safe username trading method within the community, by the
community, for the community. It’s similar to bitswap but for names ;)
check it out lmk what you think 🙏🏼 Looking to start testing our automated
system within a week or so (uses identity)

**Comment by tijno** [comment]
@slydisciplecom this is fixed now - `@chessclub` avatar shows up correctly.

**Pull request merged**
