### PR TITLE
Posts can't have JUST whitespaces

### PR DESCRIPTION
**Pull request by AdityaChaudhary0005**
BitClout.com allows users to do posts which have nothing but "JUST" white-spaces.
For example:
Screenshot from 2021-07-12 15-31-57

This PR solves this problem. Now users can't post with just blank-spaces. This applies to comments/quotes as well

### CODE REVIEW

**Comment by tijno** [comment]
would this not stop you from posting a post with just an image - which i think is currently allowed?

**Comment by AdityaChaudhary0005** [comment]
it's ok to post with just an image :) infact twitter has this feature too!

sometimes memers/artists would like to post an image without saying anything..

though i would like to listen the opinion of @lazynina or @maebeam

**Comment by AdityaChaudhary0005** [comment]
oops, i misunderstood what you said Tijn.
yeah, you are right. i will change this ASAP

**Comment by AdityaChaudhary0005** [comment]
I need to close this PR right now since i am not able to upload image from external node to test this. I will submit the PR later with successful testing.

**Pull request closed without merging**
