### PR TITLE
add verify & reserved badges to hodlr page

### PR DESCRIPTION
**Pull request by tijno**
Latest scam seems to use fake profiles that look like verified usernames with same profile image in holder page of scam / rug pull coins. 

Several users suggested adding the verified badge to the view of hodlr.

This achieves that. Hopefully.

### CODE REVIEW

**Comment by tijno** [comment]
adding it also to trade creator page.

**Comment by maebeam** [comment]
Thanks for the PR! I'll work on merging this today. For frontend PRs it would be great if you could include a screenshot in the description :)

**Comment by tijno** [comment]
image

image

@maebeam yes of course

**Comment by tijno** [comment]
@maebeam is this live on bitclout.com yet as if it is - its not working. Looks like the frontend image was updated after this was merged, but maybe not updated on bitclout.com ?

**Comment by maebeam** [comment]
we haven't deployed the frontend yet. it will go live this weekend sometime

**Comment by tijno** [comment]
looks like its live! thx

**Pull request merged**
